# Generated by Django 5.0.7 on 2024-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurovart', '0002_payments_customers_cus_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='order_id',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
