# Generated by Django 5.0.7 on 2024-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurovart', '0004_wallet_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField()),
                ('request_amount', models.FloatField()),
                ('wallet_address', models.CharField(max_length=255)),
                ('service_charge', models.FloatField()),
                ('charge_amount', models.FloatField(editable=False)),
                ('final_amount', models.FloatField(editable=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPT', 'Accept'), ('CANCEL', 'Cancel')], default='PENDING', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payouts',
            },
        ),
    ]
