# Generated by Django 5.0.7 on 2024-07-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurovart', '0007_payments_remark_admin_payments_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouts',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
