# Generated by Django 5.0.7 on 2024-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurovart', '0008_alter_payouts_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(choices=[('', '--Select--'), ('+1', 'United States (+1)'), ('+91', 'India (+91)')], max_length=10)),
                ('whatsapp_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('residential_address', models.TextField()),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_upload', models.FileField(upload_to='uploads/')),
                ('performance_link', models.URLField()),
                ('terms', models.BooleanField(default=False)),
            ],
        ),
    ]
