# Generated by Django 5.0.7 on 2024-07-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurovart', '0009_applyforfund'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentForFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'investmentforfund',
            },
        ),
        migrations.AddField(
            model_name='applyforfund',
            name='cus_id',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
