# Generated by Django 5.0.7 on 2024-08-02 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurovart', '0011_investmentforfund_invested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentforfund',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentforfund',
            name='last_credit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
