# Generated by Django 5.0.7 on 2024-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurovart', '0012_investmentforfund_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentforfund',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
