# Generated by Django 5.0.7 on 2024-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurovart', '0013_alter_investmentforfund_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
