# Generated by Django 5.0.7 on 2024-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurovart', '0014_customers_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
